#!/usr/bin/env bash
# build-index.sh — regenerate INDEX.md from current state of local-forks repo.
#
# Called as the last in-skill step (before commit) of /reflect-session Step 6
# and /sync-upstream Step 7. Output is intended to be committed alongside the
# fork changes themselves so INDEX.md stays in sync with the repo.
#
# Idempotent: running twice with no fork changes produces identical output
# except for the "last regenerated" timestamp line.

set -euo pipefail

LOCAL_FORKS="${LOCAL_FORKS:-${HOME}/.claude/local-forks}"
INDEX="${LOCAL_FORKS}/INDEX.md"

cd "${LOCAL_FORKS}"

# Skip system top-level dirs that share the same depth as marketplaces.
# Keep this list in sync with the case in bootstrap.sh (marketplace skip-list)
# so a fork dropped into _local/ or _archived/ never leaks into INDEX.md.
is_system_dir() {
  case "$1" in
    _system|_meta|_sessions|_tracked|_local|_archived) return 0 ;;
    *) return 1 ;;
  esac
}

{
  echo "# Fork index"
  echo
  echo "Auto-generated by \`_system/scripts/build-index.sh\`."
  echo "Do not edit by hand — overwritten on next \`/reflect-session\` or \`/sync-upstream\`."
  echo
  echo "Last regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo

  rows=""
  while IFS= read -r meta; do
    [[ -z "${meta}" ]] && continue
    plugin_dir="$(dirname "${meta}")"
    rel="${plugin_dir#./}"
    marketplace="$(echo "${rel}" | cut -d/ -f1)"
    plugin="$(echo "${rel}" | cut -d/ -f2)"
    is_system_dir "${marketplace}" && continue

    if ! jq -e '.' "${meta}" >/dev/null 2>&1; then
      rows+="| ${marketplace} | ${plugin} | — | — | ⚠ malformed _meta.json | — | — |"$'\n'
      continue
    fi

    baseline="$(jq -r '.baseline_upstream_version // "—"' "${meta}")"
    synced="$(jq -r '.last_synced_at // "—"' "${meta}")"

    while IFS= read -r intent; do
      [[ -z "${intent}" ]] && continue
      intent_dir="$(dirname "${intent}")"
      rel_intent="${intent_dir#${plugin_dir}/}"
      kind="$(echo "${rel_intent}" | cut -d/ -f1)"
      name="$(basename "${intent_dir}")"
      # Skills are nested one extra level: skills/<name>/SKILL.intent.md.
      # Agents/commands are flat: agents/<name>.intent.md (intent_dir == agents).
      # Disambiguate by checking whether the intent file basename matches `<name>.intent.md`.
      intent_base="$(basename "${intent}" .intent.md)"
      if [[ "${kind}" == "agents" || "${kind}" == "commands" ]]; then
        name="${intent_base}"
      fi

      improvements="$(grep -cE '^#{2,3} Improvement #' "${intent}" 2>/dev/null || echo 0)"

      rows+="| ${marketplace} | ${plugin} | ${kind} | ${name} | ${baseline} | ${improvements} | ${synced} |"$'\n'
    done < <(find "${plugin_dir}" -name "*.intent.md" 2>/dev/null | sort)
  done < <(find . -mindepth 3 -maxdepth 3 -name "_meta.json" 2>/dev/null | sort)

  if [[ -z "${rows}" ]]; then
    echo "_No forks yet. The first \`/reflect-session\` finding of category B will create one._"
  else
    echo "| Marketplace | Plugin | Kind | Name | Baseline | Improvements | Last Synced |"
    echo "|---|---|---|---|---|---|---|"
    printf '%s' "${rows}"
  fi
} > "${INDEX}.tmp"

mv "${INDEX}.tmp" "${INDEX}"

echo "Regenerated ${INDEX}"
